# Generated by Django 3.1.7 on 2021-03-30 02:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date_of_booking', models.DateTimeField(default=django.utils.timezone.now)),
                ('in_time', models.DateTimeField(blank=True, null=True)),
                ('out_time', models.DateTimeField(blank=True, null=True)),
                ('occupancy', models.IntegerField()),
                ('dues', models.IntegerField(default=0)),
                ('advance', models.IntegerField(default=0)),
            ],
        ),
    ]
