# Generated by Django 3.1.7 on 2021-03-30 03:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0002_bookinglist_user1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinglist',
            name='advance',
        ),
        migrations.RemoveField(
            model_name='bookinglist',
            name='dues',
        ),
        migrations.RemoveField(
            model_name='bookinglist',
            name='user1',
        ),
        migrations.CreateModel(
            name='AdminEditList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dues', models.IntegerField(default=0)),
                ('advance', models.IntegerField(default=0)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
